"""Make valid_until nullable in SSLLog

Revision ID: 05c4419864ff
Revises: eb8212576f2d
Create Date: 2025-07-13 11:06:37.378158

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05c4419864ff"
down_revision: Union[str, None] = "eb8212576f2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ssllog", "valid_until", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ssllog", "valid_until", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
