"""add indexes to website model

Revision ID: bf145efa0379
Revises: 772155fc4fd5
Create Date: 2025-03-04 20:38:48.447824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf145efa0379'
down_revision: Union[str, None] = '772155fc4fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_website_ssl_expiry_date'), 'website', ['ssl_expiry_date'], unique=False)
    op.create_index(op.f('ix_website_url'), 'website', ['url'], unique=False)
    op.create_index(op.f('ix_website_user_id'), 'website', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_user_id'), table_name='website')
    op.drop_index(op.f('ix_website_url'), table_name='website')
    op.drop_index(op.f('ix_website_ssl_expiry_date'), table_name='website')
    # ### end Alembic commands ###
