"""Add check_type field to Website

Revision ID: eb8212576f2d
Revises: aa8e65f99f21
Create Date: 2025-06-28 12:56:34.653501

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb8212576f2d"
down_revision: Union[str, None] = "aa8e65f99f21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the CheckType enum type
checktype_enum = sa.Enum("HTTP", "PING", name="checktype")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    checktype_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("website", sa.Column("check_type", checktype_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("website", "check_type")

    # Drop the enum type
    checktype_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
